---
repo-name: peripherals-cherwell
categories:
- Service Management
- DevOps
- Ticketing
display-name: Cherwell
manufacture: Cherwell
product: Cherwell
description: Cherwell Service Management provides a powerful and flexible IT service management (ITSM) platform for service desk teams that need to move fast and can't afford to be constrained by technology.
